import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { client } from "../src/sanity/client";
import { SanityDocument } from "next-sanity";
import { navigationQuery } from "../src/sanity/queries";
import { NavigationQueryResult } from "../src/sanity/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navigationItems = await client.fetch<NavigationQueryResult>(
    navigationQuery,
  );

  console.log(navigationItems);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {navigationItems?.items?.map(item => (
          <div key={item._key}>{item.label}</div>
        ))}
        
      </body>
    </html>
  );
}
