/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Video = {
  _type: "video";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  caption?: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type NavDropdownItem = {
  _type: "navDropdownItem";
  label?: string;
  page?: PageReference;
};

export type NavDropdown = {
  _type: "navDropdown";
  label?: string;
  items?: Array<
    {
      _key: string;
    } & NavDropdownItem
  >;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  page?: PageReference;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<
    | ({
        _key: string;
      } & NavLink)
    | ({
        _key: string;
      } & NavDropdown)
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageGallery = {
  _type: "imageGallery";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type ColumnText = {
  _type: "columnText";
  col1?: BlockContent;
  col2?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?:
        | "normal"
        | "pageTitle"
        | "sectionTitle"
        | "h1"
        | "h2"
        | "h3"
        | "h4"
        | "h5"
        | "h6";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Anchor
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ColumnText)
  | ({
      _key: string;
    } & ImageGallery)
  | ({
      _key: string;
    } & Table)
  | ({
      _key: string;
    } & Video)
>;

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  isHome?: boolean;
  showPrevNextNav?: boolean;
  content?: BlockContent;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Anchor = {
  _type: "anchor";
  label?: string;
  slug?: Slug;
  hidden?: boolean;
};

export type Table = {
  _type: "table";
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityFileAssetReference
  | Video
  | PageReference
  | NavDropdownItem
  | NavDropdown
  | NavLink
  | Navigation
  | SanityImageAssetReference
  | ImageGallery
  | ColumnText
  | BlockContent
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Anchor
  | Table
  | TableRow
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ..\web\src\sanity\queries.ts
// Variable: slugsQuery
// Query: *[    _type == "page" &&    defined(slug.current) &&    isHome != true  ]{    "slug": slug.current  }
export type SlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: ..\web\src\sanity\queries.ts
// Variable: homepageQuery
// Query: *[_type == "page" && isHome == true][0]{    _id,    title,    showPrevNextNav,    content[]{      ...,      _type == "video" => {        caption,        "url": file.asset->url,        "mimeType": file.asset->mimeType      }    }  }
export type HomepageQueryResult = {
  _id: string;
  title: string | null;
  showPrevNextNav: boolean | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal"
          | "pageTitle"
          | "sectionTitle";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          {
            _key: string;
          } & Anchor
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "columnText";
        col1?: BlockContent;
        col2?: BlockContent;
      }
    | {
        _key: string;
        _type: "imageGallery";
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          caption?: string;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "table";
        rows?: Array<
          {
            _key: string;
          } & TableRow
        >;
      }
    | {
        _key: string;
        _type: "video";
        file?: {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "file";
        };
        caption: string | null;
        url: string | null;
        mimeType: string | null;
      }
  > | null;
} | null;

// Source: ..\web\src\sanity\queries.ts
// Variable: pageBySlugQuery
// Query: {    "page": *[      _type == "page" &&      slug.current == $slug &&       isHome != true    ][0]{      _id,      title,      showPrevNextNav,      content[]{        ...,        _type == "video" => {          caption,          "url": file.asset->url,          "mimeType": file.asset->mimeType        }      },      "slug": slug.current,      "navContext": *[_type == "navigation"][0]{        "dropdown": items[          _type == "navDropdown" &&           (count(items[page._ref == ^.^.^._id]) > 0)        ][0] {          ...,          items[]{            ...,            "slug": page->slug.current          }        }      }    }  }
export type PageBySlugQueryResult = {
  page: {
    _id: string;
    title: string | null;
    showPrevNextNav: boolean | null;
    content: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal"
            | "pageTitle"
            | "sectionTitle";
          listItem?: "bullet" | "number";
          markDefs?: Array<
            {
              _key: string;
            } & Anchor
          >;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          _key: string;
          _type: "columnText";
          col1?: BlockContent;
          col2?: BlockContent;
        }
      | {
          _key: string;
          _type: "imageGallery";
          images?: Array<{
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            caption?: string;
            alt?: string;
            _type: "image";
            _key: string;
          }>;
        }
      | {
          _key: string;
          _type: "table";
          rows?: Array<
            {
              _key: string;
            } & TableRow
          >;
        }
      | {
          _key: string;
          _type: "video";
          file?: {
            asset?: SanityFileAssetReference;
            media?: unknown;
            _type: "file";
          };
          caption: string | null;
          url: string | null;
          mimeType: string | null;
        }
    > | null;
    slug: string | null;
    navContext: {
      dropdown: {
        _key: string;
        _type: "navDropdown";
        label?: string;
        items: Array<{
          _key: string;
          _type: "navDropdownItem";
          label?: string;
          page?: PageReference;
          slug: string | null;
        }> | null;
      } | null;
    } | null;
  } | null;
};

// Source: ..\web\src\sanity\queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation"][0]{    items[]{      _type,      _key,      label,      _type == "navLink" => {        "slug": page->slug.current      },      _type == "navDropdown" => {        items[]{          label,          _key,          "slug": page->slug.current        }      }    }  }
export type NavigationQueryResult = {
  items: Array<
    | {
        _type: "navDropdown";
        _key: string;
        label: string | null;
        items: Array<{
          label: string | null;
          _key: string;
          slug: string | null;
        }> | null;
      }
    | {
        _type: "navLink";
        _key: string;
        label: string | null;
        slug: string | null;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "page" &&\n    defined(slug.current) &&\n    isHome != true\n  ]{\n    "slug": slug.current\n  }\n': SlugsQueryResult;
    '\n  *[_type == "page" && isHome == true][0]{\n    _id,\n    title,\n    showPrevNextNav,\n    content[]{\n      ...,\n      _type == "video" => {\n        caption,\n        "url": file.asset->url,\n        "mimeType": file.asset->mimeType\n      }\n    }\n  }\n': HomepageQueryResult;
    '\n  {\n    "page": *[\n      _type == "page" &&\n      slug.current == $slug && \n      isHome != true\n    ][0]{\n      _id,\n      title,\n      showPrevNextNav,\n      content[]{\n        ...,\n        _type == "video" => {\n          caption,\n          "url": file.asset->url,\n          "mimeType": file.asset->mimeType\n        }\n      },\n      "slug": slug.current,\n      "navContext": *[_type == "navigation"][0]{\n        "dropdown": items[\n          _type == "navDropdown" && \n          (count(items[page._ref == ^.^.^._id]) > 0)\n        ][0] {\n          ...,\n          items[]{\n            ...,\n            "slug": page->slug.current\n          }\n        }\n      }\n    }\n  }\n': PageBySlugQueryResult;
    '\n  *[_type == "navigation"][0]{\n    items[]{\n      _type,\n      _key,\n      label,\n      _type == "navLink" => {\n        "slug": page->slug.current\n      },\n      _type == "navDropdown" => {\n        items[]{\n          label,\n          _key,\n          "slug": page->slug.current\n        }\n      }\n    }\n  }\n': NavigationQueryResult;
  }
}
